/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui.cadastros;

import banco.contas.Conta;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 * Essa é uma classe abstrata que nunca deve ser instanciada diretamente
 * apenas herdada.
 * É usada aqui no projeto para evitar replicação de código.
 * O método salvarCadastro deve ser implementado em todas as classes filhas.
 * @author Manoel Vilela
 */
public abstract class Cadastro extends javax.swing.JPanel {

    private Conta conta;
    
    abstract void salvarCadastro();
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }
    
    public void submeterCadastro() {
        try {
            this.salvarCadastro();
            this.proximoCadastro();
        } catch (Exception e) {
            this.dialogPreenchaTodosCampos();
        }
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }
    
    public Conta getConta() {
        return this.conta;
    }
    
    public void proximoCadastro() {
        Container c = this.getParent();
        CardLayout l = (CardLayout) c.getLayout();
        l.next(c);
    }
    
    public void voltarCadastro() {
        Container c = this.getParent();
        CardLayout l = (CardLayout) c.getLayout();
        l.previous(c);
    }
    
    public void executarFaseOperacoes() {
        Container c = this.getParent().getParent();
        CardLayout l = (CardLayout) c.getLayout();
        l.next(c);
    }
    
    public void dialogPreenchaTodosCampos() {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos campos!");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
