/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui.operacoes;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 * Classe abstrata do tipo Operacão. Deve implementar:
 * - operacao
 * - limparFields
 * 
 * 
 * @author Manoel Vilela
 */
public abstract class Operacao extends javax.swing.JPanel {
    
    protected abstract void operacao(); // realizar operação
    protected abstract void limparFields(); // limpar campos fields

    /**
     * Creates new form Operacao
     */
    public Operacao() {
        initComponents();
    }

    /**
     * Volta ao JPanel de operações
     */
    protected void voltarFaseOperacoes() {                                                
        Container c = this.getParent();
        CardLayout l = (CardLayout) c.getLayout();
        l.show(c, "operacoes");
    }
    
    /**
     * Wrapper da definição de operacao encapsulada em um try/catch block
     * Para checar se nenhum dos campos emitiu uma exceção, como parsing
     * de números dos campos.
     */
    public void submeterOperacao() {
        try {
            this.operacao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Campos inválidos.");
        }
    }
    
 
    /**
     * Termina a operação: limpa text fields e volta a fase de Operações.
     */
    public void terminarOperacao() {
        limparFields();
        voltarFaseOperacoes();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
