/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui.operacoes;

import banco.contas.Conta;


import javax.swing.JOptionPane;

/**
 * Simples view para realizar transferências entre contas
 * @author Manoel Vilela
 */
public class Transferencia extends Operacao {

    /**
     * Creates new form Transferencia
     */
    public Transferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTransferencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonTransferir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldOrigem = new javax.swing.JTextField();
        jTextFieldDestino = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();

        jLabelTransferencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTransferencia.setText("TRANSFERÊNCIA");

        jLabel2.setText("Conta Origem:");

        jLabel3.setText("Conta Destino:");

        jLabel4.setText("Valor:");

        jButtonTransferir.setText("Transferir");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabelTransferencia)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonTransferir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOrigem)
                                    .addComponent(jTextFieldDestino)
                                    .addComponent(jTextFieldValor)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVoltar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTransferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTransferir)
                    .addComponent(jButtonVoltar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.terminarOperacao();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    @Override
    protected void operacao() {
         Conta contaOrigem = Conta.buscaConta(Integer.parseInt(jTextFieldOrigem.getText()));
        Conta contaDestino = Conta.buscaConta(Integer.parseInt(jTextFieldDestino.getText()));
        double valor = Double.parseDouble(jTextFieldValor.getText());
        if (contaOrigem != null && contaDestino != null) {
            String message;
            message = valor + " :: "
                    + contaOrigem.getNome().toUpperCase()
                    + " -> "
                    + contaDestino.getNome().toUpperCase();

            int state = JOptionPane.showConfirmDialog(this, message, "Transferência",
                    JOptionPane.YES_NO_OPTION);

            if (state == JOptionPane.YES_OPTION) {
                if (contaOrigem.sacar(valor)) {
                    contaDestino.depositar(valor);
                    JOptionPane.showMessageDialog(this, "Transferência realizada!");
                } else {
                    JOptionPane.showMessageDialog(this, "Saldo insuficiente na conta de origem.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Transferência cancelada!");
            }
            this.terminarOperacao();
        } else if (contaOrigem == null & contaDestino == null) {
            JOptionPane.showMessageDialog(this, "Ambas contas não existem.");
        } else if (contaOrigem == null) {
            JOptionPane.showMessageDialog(this, "Conta de origem inexistente.");
        } else {
            JOptionPane.showMessageDialog(this, "Conta de destino inexistente.");
        }
    }
    
    @Override
    protected void limparFields() {
        jTextFieldDestino.setText("");
        jTextFieldOrigem.setText("");
        jTextFieldValor.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTransferencia;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldOrigem;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
