/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui;

import banco.contas.Conta;
import banco.gui.cadastros.Cadastro;
import java.util.ArrayList;

/**
 * Essa classe gerencia os formulários de cadastro, atualmente
 * está definido fixamente como 3 formulários como descrito na especificação:
 * - ContaComum
 * - ContaPoupanca
 * - ContaEspecial
 * 
 * Futuramente é possível adaptar para receber n formulários via polimorfismo
 * da ArrayList<Conta>, apresentando um formulário diferente de acordo com cada
 * conta instanciada.
 * @author Manoel Vilela
 */
public class FaseCadastro extends javax.swing.JPanel {

    /**
     * Creates new form FaseCadastro
     */
    public FaseCadastro() {
        initComponents();
    }
    
    /**
     * Relaciona cada formulário de cadastro com um objeto do tipo Conta
     * @param contas 
     */
    public void setContas(ArrayList<Conta> contas) {
        cadastroContaComum.setConta(contas.get(0));
        cadastroContaPoupanca.setConta(contas.get(1));
        cadastroContaEspecial.setConta(contas.get(2));
        //System.out.println(cadastroContaComum1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroContaComum = new banco.gui.cadastros.CadastroContaComum();
        cadastroContaPoupanca = new banco.gui.cadastros.CadastroContaPoupanca();
        cadastroContaEspecial = new banco.gui.cadastros.CadastroContaEspecial();

        setLayout(new java.awt.CardLayout());
        add(cadastroContaComum, "cadastroContaComum");
        add(cadastroContaPoupanca, "cadastroContaComum");
        add(cadastroContaEspecial, "cadastroContaComum");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private banco.gui.cadastros.CadastroContaComum cadastroContaComum;
    private banco.gui.cadastros.CadastroContaEspecial cadastroContaEspecial;
    private banco.gui.cadastros.CadastroContaPoupanca cadastroContaPoupanca;
    // End of variables declaration//GEN-END:variables
}
