/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui.operacoes;

import banco.contas.Conta;
import banco.contas.ContaPoupanca;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 * View para aplicar reajuste (lucro) para Contas Poupança.
 * @author Manoel Vilela
 */
public class Reajustar extends Operacao {

    /**
     * Creates new form Reajustar
     */
    public Reajustar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldConta = new javax.swing.JTextField();
        jTextFieldReajuste = new javax.swing.JTextField();
        jButtonReajustar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelSaque = new javax.swing.JLabel();
        jLabelConta = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();

        jTextFieldConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaActionPerformed(evt);
            }
        });

        jTextFieldReajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReajusteActionPerformed(evt);
            }
        });

        jButtonReajustar.setText("Reajustar");
        jButtonReajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReajustarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelSaque.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSaque.setText("REAJUSTE");

        jLabelConta.setText("Conta Poupança: ");

        jLabelValor.setText("Taxa de Reajuste:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldReajuste))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVoltar)
                                .addGap(71, 71, 71)
                                .addComponent(jButtonReajustar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabelSaque)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaque)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConta)
                    .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReajustar)
                    .addComponent(jButtonVoltar))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jTextFieldContaActionPerformed

    private void jTextFieldReajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReajusteActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jTextFieldReajusteActionPerformed

    private void jButtonReajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReajustarActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jButtonReajustarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.terminarOperacao();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    @Override
    protected void limparFields() {
        jTextFieldConta.setText("");
        jTextFieldReajuste.setText("");
    }

    @Override
    protected void operacao() {
        Conta conta = Conta.buscaConta(Integer.parseInt(jTextFieldConta.getText()));
        if (conta == null) {
            JOptionPane.showMessageDialog(this, "Conta não encontrada!");
        } else if (!conta.tipoConta().equals("Conta Poupança")) {
            JOptionPane.showMessageDialog(this, "Conta não é do tipo poupança!");
        } else {
            ContaPoupanca contaPoupanca = (ContaPoupanca) conta;
            String reajuste = jTextFieldReajuste.getText();
            if (reajuste.length() > 0) {
                contaPoupanca.reajustar(Double.parseDouble(reajuste));
            } else {
                contaPoupanca.reajustar();
            }
            JOptionPane.showMessageDialog(this, "Ajuste realizado com sucesso!");
            this.terminarOperacao();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReajustar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelConta;
    private javax.swing.JLabel jLabelSaque;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldConta;
    private javax.swing.JTextField jTextFieldReajuste;
    // End of variables declaration//GEN-END:variables
}
