/*
 * Copyright 2017 Manoel Vilela <manoel_vilela@engineer.com>
 */
package banco.gui.operacoes;

import banco.contas.Conta;
import javax.swing.JOptionPane;

/**
 * View para gerenciamento de saques.
 *
 * @author Manoel Vilela
 */
public class Saque extends Operacao {

    /**
     * Creates new form Saldos
     */
    public Saque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConta = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldConta = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonSacar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelSaque = new javax.swing.JLabel();

        jLabelConta.setText("Conta:");

        jLabelValor.setText("Valor:");

        jTextFieldConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaActionPerformed(evt);
            }
        });

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jButtonSacar.setText("Sacar");
        jButtonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelSaque.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSaque.setText("SAQUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(jButtonSacar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelConta)
                                    .addComponent(jLabelValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValor)
                                    .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelSaque)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConta)
                    .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacar)
                    .addComponent(jButtonVoltar))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacarActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jButtonSacarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.terminarOperacao();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaActionPerformed
        this.submeterOperacao();
    }//GEN-LAST:event_jTextFieldContaActionPerformed

    @Override
    protected void operacao() {
        String mensagem;
        Conta conta = Conta.buscaConta(Integer.parseInt(jTextFieldConta.getText()));
        double valor = Double.parseDouble(jTextFieldValor.getText());

        if (conta == null) {
            JOptionPane.showMessageDialog(this, "Conta inexistente");
            return;
        }

        int state = JOptionPane.showConfirmDialog(this,
                "Nome da conta: " + conta.getNome().toUpperCase(),
                "Saque",
                JOptionPane.YES_NO_OPTION);

        if (state == JOptionPane.YES_OPTION) {
            if (conta.sacar(valor)) {
                if (conta.getSaldo() < 0) {
                    mensagem = "Saque efetuado usando cheque especial";
                } else {
                    mensagem = "Saque efetuado com sucesso";
                }
            } else {
                mensagem = "Saldo inuficiente";
            }
        } else {
            mensagem = "Saque cancelado!";
        }
        JOptionPane.showMessageDialog(this, mensagem);
        terminarOperacao();
    }
    
    @Override
    protected void limparFields() {
        jTextFieldConta.setText("");
        jTextFieldValor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelConta;
    private javax.swing.JLabel jLabelSaque;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldConta;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
